kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: java-app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: myapp
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service: 
                name: java-app
                port: 
                  number: 80
