Kind: Ingress
apiVersion: networking.io/V1
metadata:
  name: java-app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: myapp
    http:
    - path: /app1
      pathType: prefix
      backend:
        service: 
          name: java-app
          port: 
            number: 80
  
